// ─── gmailSender.js ──────────────────────────────────────────────────────────
// Sends emails via Gmail using the Anthropic API + Gmail MCP.
// The Gmail MCP is connected via claude.ai OAuth — no extra setup needed
// as long as the user has Gmail connected in their Claude account.

export async function sendViaGmail({ to, toName, subject, body }) {
  const res = await fetch("/api/send-email", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ to, toName, subject, body }),
  });

  if (!res.ok) {
    const data = await res.json().catch(() => ({}));
    throw new Error(data.error || `Send failed (${res.status})`);
  }

  return { success: true };
}

// ─── Email body builder ───────────────────────────────────────────────────────
export function buildEmailBody({
  note,
  linkedinPost,
  twitterPost,
  newsletter,
  firstName,
  company,
  interviewSource,
  interviewTopic,
  specificMoment,
  demoLink,
  yourName,
  include = { linkedin: true, twitter: true, newsletter: true },
}) {
  // Extract first paragraph of LinkedIn post as the preview snippet
  const linkedinPreview = linkedinPost
    ? linkedinPost.split("\n\n")[0].trim()
    : "";

  // Replace all template variables in the note
  const rendered = (note || "")
    .replace(/\{\{first_name\}\}/g, firstName || "")
    .replace(/\{\{company\}\}/g, company || "")
    .replace(/\{\{interview_source\}\}/g, interviewSource || "the interview")
    .replace(/\{\{interview_topic\}\}/g, interviewTopic || "your journey")
    .replace(/\{\{specific_moment\}\}/g, specificMoment || "your insights")
    .replace(/\{\{linkedin_post_preview\}\}/g, linkedinPreview)
    .replace(/\{\{demo_link\}\}/g, demoLink || "https://usekorel.com/demo")
    .replace(/\{\{your_name\}\}/g, yourName || "Saqib");

  const DIV = "——————————————————";

  // Format X thread as numbered lines if not already (1/ 2/ 3/ ...)
  function formatXThread(raw) {
    if (!raw) return "";
    const lines = raw.split("\n").map((l) => l.trim()).filter(Boolean);
    // Already numbered (starts with "1/")
    if (lines[0]?.startsWith("1/")) return raw;
    // Number each line
    return lines.map((l, i) => `${i + 1}/ ${l}`).join("\n");
  }

  // Build the full pack section (appended after the note)
  const sections = [];

  if (include.linkedin && linkedinPost) {
    sections.push(`${DIV}\n🔴 FULL LINKEDIN POST\n${DIV}\n\n${linkedinPost}`);
  }
  if (include.twitter && twitterPost) {
    sections.push(`${DIV}\n𝕏 POST\n${DIV}\n\n${formatXThread(twitterPost)}`);
  }
  if (include.newsletter && newsletter) {
    sections.push(`${DIV}\n📰 NEWSLETTER SECTION\n${DIV}\n\n${newsletter}`);
  }

  const packSection =
    sections.length > 0
      ? `\n\n\nP.S. — Here's the full pack in case you want to use any of it:\n\n` +
        sections.join("\n\n\n")
      : "";

  return (
    rendered +
    packSection +
    `\n\n${DIV}\nGenerated by Korel · usekorel.com`
  );
}
