// ─── gmailSender.js ──────────────────────────────────────────────────────────
// Sends emails via Gmail using the Anthropic API + Gmail MCP.
// Requires NEXT_PUBLIC_ANTHROPIC_API_KEY (or pass key at runtime).
// The Gmail MCP is connected via claude.ai OAuth — no extra setup needed
// as long as the user has Gmail connected in their Claude account.

export async function sendViaGmail({ to, toName, subject, body }) {
  const res = await fetch("/api/send-email", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ to, subject, body }),
  });

  if (!res.ok) {
    const data = await res.json().catch(() => ({}));
    throw new Error(data.error || `Send failed (${res.status})`);
  }

  return { success: true };
}

// ─── Email body builder ───────────────────────────────────────────────────────
export function buildEmailBody({ note, linkedinPost, twitterPost, newsletter, firstName, company, include = { linkedin: true, twitter: true, newsletter: true } }) {
  const rendered = note
    .replace(/\{\{first_name\}\}/g, firstName || "")
    .replace(/\{\{company\}\}/g, company || "");

  const sections = [];
  if (include.linkedin && linkedinPost) {
    sections.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n📌 LINKEDIN POST\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n${linkedinPost}`);
  }
  if (include.twitter && twitterPost) {
    sections.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n𝕏  POST\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n${twitterPost}`);
  }
  if (include.newsletter && newsletter) {
    sections.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n📰 NEWSLETTER\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n${newsletter}`);
  }

  return [rendered, ...sections].join("\n\n\n") + "\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nGenerated by Korel · usekorel.com";
}
