"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Loader2, Sparkles } from "lucide-react";
import { AuthorityPackPreview } from "./AuthorityPackPreview";
import { UpgradeModal } from "./UpgradeModal";

type PacksResponse = {
  packs?: { id: string }[];
  generated?: number;
  remaining?: number | null;
  plan?: string;
  monthlyLimit?: number | null;
  planLimits?: {
    maxRegenerationsPerPack?: number | null;
    maxStoredPacks?: number | null;
    repurposeAccess?: boolean;
    qualityFixAccess?: boolean;
  };
  code?: string;
  ok?: boolean;
  upgradeHint?: boolean;
  error?: "plan_limit_reached" | "limit_reached" | "quota" | "INVALID_INPUT" | "invalid" | "generation_failed" | "transcript_unavailable";
  detail?: string;
  message?: string;
  lastCreatedId?: string;
};

export default function NewPackPage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const initialInput = useMemo(() => (searchParams?.get("input") ?? "").trim(), [searchParams]);
  // ?prefill= pre-fills the textarea without triggering auto-generation
  const prefillInput = useMemo(() => (searchParams?.get("prefill") ?? "").trim(), [searchParams]);

  const [sourceInput, setSourceInput] = useState("");
  const [episodeTitle, setEpisodeTitle] = useState("");
  const [inputType, setInputType] = useState("INTERVIEW");
  const [angle, setAngle] = useState("THOUGHT_LEADERSHIP");
  const [isGenerating, setIsGenerating] = useState(false);

  const [remaining, setRemaining] = useState<number>(Infinity);
  const [monthlyLimit, setMonthlyLimit] = useState<number>(3);
  const [packsThisMonth, setPacksThisMonth] = useState<number>(0);
  const [plan, setPlan] = useState<string>("FREE");
  const [maxRegenerationsPerPack, setMaxRegenerationsPerPack] = useState<number | null>(null);
  const [countsLoaded, setCountsLoaded] = useState(false);

  const autoGeneratedRef = useRef(false);
  const [successMessage, setSuccessMessage] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const [hasGenerated, setHasGenerated] = useState(false);
  const [activePackId, setActivePackId] = useState<string | null>(null);
  const [showUpgradeModal, setShowUpgradeModal] = useState(false);
  const [allTimePacks, setAllTimePacks] = useState<number | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);

  useEffect(() => {
    if (!initialInput) return;
    setSourceInput((current) => (current.trim() ? current : initialInput));
  }, [initialInput]);

  // Pre-fill only â€” does NOT trigger auto-generation
  useEffect(() => {
    if (!prefillInput) return;
    setSourceInput((current) => (current.trim() ? current : prefillInput));
  }, [prefillInput]);

  const applyResponse = useCallback((data: PacksResponse) => {
    if (data.remaining === null) setRemaining(Infinity);
    if (typeof data.remaining === "number") setRemaining(data.remaining);
    if (data.monthlyLimit === null) setMonthlyLimit(Infinity);
    if (typeof data.monthlyLimit === "number") setMonthlyLimit(data.monthlyLimit);
    if (typeof data.generated === "number") setPacksThisMonth(data.generated);
    if (typeof data.plan === "string") setPlan(data.plan);
    if (data.planLimits && "maxRegenerationsPerPack" in data.planLimits) {
      const limit = data.planLimits.maxRegenerationsPerPack;
      setMaxRegenerationsPerPack(typeof limit === "number" ? limit : null);
    }
  }, []);

  useEffect(() => {
    const loadCounts = async () => {
      try {
        const response = await fetch("/api/packs");
        const data = (await response.json()) as PacksResponse;
        applyResponse(data);
        setAllTimePacks(data.packs?.length ?? 0);
      } catch (error) {
        console.error(error);
        setAllTimePacks(0);
      } finally {
        setCountsLoaded(true);
      }
    };
    void loadCounts();
  }, [applyResponse]);

  // Auto-focus textarea when not auto-generating from ?input=
  useEffect(() => {
    if (!initialInput && countsLoaded) {
      textareaRef.current?.focus();
    }
  }, [initialInput, countsLoaded]);

  useEffect(() => {
    if (!initialInput || !countsLoaded || autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;
    void handleGenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialInput, countsLoaded]);

  const EXAMPLE_URLS = [
    { label: "Naval Ravikant â€” How to Get Rich", url: "https://www.youtube.com/watch?v=1-TZqOsVCNM" },
    { label: "Sam Altman â€” How to Build the Future", url: "https://www.youtube.com/watch?v=oBt53YbR9Kk" },
    { label: "Paul Graham â€” How to Start a Startup", url: "https://www.youtube.com/watch?v=f84LymEs67Y" },
  ] as const;

  const handleExampleClick = (url: string) => {
    setSourceInput(url);
    if (errorMessage) setErrorMessage("");
  };

  const handleGenerate = async (overrideInput?: string) => {
    const inputValue = (overrideInput ?? sourceInput).trim();
    if (isGenerating || !inputValue || remaining <= 0) return;

    setIsGenerating(true);
    setSuccessMessage("");
    setErrorMessage("");

    try {
      const response = await fetch("/api/packs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ input: inputValue, title: episodeTitle.trim() || undefined, inputType, angle }),
      });
      let data: PacksResponse = {};
      try {
        data = (await response.json()) as PacksResponse;
      } catch {
        data = {};
      }

      const isPlanLimit =
        data.code === "PLAN_LIMIT_PACKS_EXCEEDED" ||
        data.error === "plan_limit_reached" ||
        data.error === "limit_reached" ||
        response.status === 403;
      if (isPlanLimit) {
        setRemaining(0);
        setShowUpgradeModal(true);
      } else if (data.error === "INVALID_INPUT" || data.error === "invalid") {
        setErrorMessage("Please add a valid link or transcript (min 200 characters).");
      } else if (data.error === "transcript_unavailable") {
        setErrorMessage(
          "Captions are disabled for this video. Open the video on YouTube, click â‹¯ â†’ Show transcript, copy the text, and paste it here directly.",
        );
      } else if (data.error === "generation_failed") {
        setErrorMessage(`Generation failed: ${data.detail ?? "unknown error"}`);
      } else if (response.ok) {
        setSourceInput("");
        setSuccessMessage("Pack generated.");
        setHasGenerated(true);
        if (data.lastCreatedId) {
          setActivePackId(data.lastCreatedId);
        }
      } else {
        setErrorMessage("Something went wrong. Please try again.");
      }

      applyResponse(data);
    } catch (error) {
      console.error(error);
      setErrorMessage("Something went wrong. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const limitReached = remaining <= 0;
  const isGenerateDisabled = isGenerating || !sourceInput.trim() || limitReached;

  const effectiveLimit = monthlyLimit === Infinity ? null : monthlyLimit;
  const progressPercent = effectiveLimit
    ? Math.min(100, Math.round((packsThisMonth / effectiveLimit) * 100))
    : 0;

  return (
    <>
      {showUpgradeModal && (
        <UpgradeModal
          currentPlan={plan}
          onClose={() => setShowUpgradeModal(false)}
        />
      )}

      <div className="flex-1 flex flex-col md:flex-row">
        <section className="w-full md:w-[30%] border-b border-[#E2E8F0] md:border-b-0 md:border-r p-8">
          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Source</h2>
            <p className="text-sm text-[#64748B]">
              Turn a talk, podcast, or internal memo into a week of authority content.
            </p>
          </div>

          <div className="mt-6 space-y-5">
            <div className="space-y-2">
              <label className="text-sm font-medium text-[#334155]" htmlFor="source-input">
                Input
              </label>
              <textarea
                ref={textareaRef}
                id="source-input"
                rows={6}
                placeholder="Paste a YouTube link or transcript..."
                className="w-full resize-none rounded-lg border border-[#E2E8F0] bg-white px-3 py-2 text-sm text-[#0F172A] placeholder:text-[#94A3B8] focus:border-[#4F46E5] focus:outline-none focus:ring-2 focus:ring-[#4F46E5]"
                value={sourceInput}
                onChange={(event) => {
                  setSourceInput(event.target.value);
                  if (errorMessage) setErrorMessage("");
                  if (successMessage) setSuccessMessage("");
                }}
              />
              <p className="text-xs text-[#94A3B8]">
                We extract your strategic insights first Ã¢â‚¬â€ then generate platform-ready assets.
              </p>
            </div>

            <div className="space-y-1.5">
              <label className="text-sm font-medium text-[#334155]" htmlFor="input-type">
                Input Type
              </label>
              <select
                id="input-type"
                value={inputType}
                onChange={(e) => setInputType(e.target.value)}
                className="w-full rounded-lg border border-[#E2E8F0] bg-white px-3 py-2 text-sm text-[#0F172A] focus:border-[#4F46E5] focus:outline-none focus:ring-2 focus:ring-[#4F46E5]"
              >
                <option value="INTERVIEW">Interview</option>
                <option value="PRODUCT_UPDATE">Product Update</option>
                <option value="INVESTOR_UPDATE">Investor Update</option>
                <option value="STRATEGY_MEMO">Strategy Memo</option>
                <option value="CUSTOMER_STORY">Customer Story</option>
                <option value="CUSTOM">Custom</option>
              </select>
              <p className="text-xs text-[#94A3B8]">
                Different document types shape structure and positioning.
              </p>
            </div>

            <div className="space-y-1.5">
              <label className="text-sm font-medium text-[#334155]" htmlFor="angle">
                Angle
              </label>
              <select
                id="angle"
                value={angle}
                onChange={(e) => setAngle(e.target.value)}
                className="w-full rounded-lg border border-[#E2E8F0] bg-white px-3 py-2 text-sm text-[#0F172A] focus:border-[#4F46E5] focus:outline-none focus:ring-2 focus:ring-[#4F46E5]"
              >
                <option value="THOUGHT_LEADERSHIP">Thought Leadership</option>
                <option value="TACTICAL">Tactical</option>
                <option value="CONTRARIAN">Contrarian</option>
                <option value="STORY_DRIVEN">Story-Driven</option>
                <option value="VISIONARY">Visionary</option>
                <option value="EXECUTION_FOCUSED">Execution-Focused</option>
              </select>
              <p className="text-xs text-[#94A3B8]">
                Same source, different positioning lens.
              </p>
            </div>

            {allTimePacks === 0 && !hasGenerated && !sourceInput.trim() && (
              <div className="rounded-lg border border-[#E2E8F0] bg-[#F8FAFC] px-4 py-3 space-y-2">
                <p className="text-xs font-medium text-[#475569]">Try an example:</p>
                <div className="space-y-1">
                  {EXAMPLE_URLS.map(({ label, url }) => (
                    <button
                      key={url}
                      type="button"
                      onClick={() => handleExampleClick(url)}
                      className="w-full text-left rounded-md px-2 py-1.5 text-xs text-[#4F46E5] hover:bg-[#EEF2FF] transition-colors truncate"
                    >
                      {label}
                    </button>
                  ))}
                </div>
              </div>
            )}

            <div>
              <label
                htmlFor="transcript-upload"
                className="flex cursor-pointer flex-col items-center justify-center gap-1 rounded-lg border-2 border-dashed border-[#E2E8F0] px-6 py-8 text-center text-sm text-[#64748B] hover:bg-[#F1F5F9]"
              >
                <span className="font-medium text-[#475569]">Click to upload or drag and drop</span>
                <span className="text-xs text-[#94A3B8]">.txt, .srt, .vtt files</span>
              </label>
              <input id="transcript-upload" type="file" className="hidden" accept=".txt,.srt,.vtt" />
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium text-[#334155]" htmlFor="episode-title">
                Episode Title
              </label>
              <input
                id="episode-title"
                type="text"
                placeholder="Enter episode title..."
                className="w-full rounded-lg border border-[#E2E8F0] bg-white px-3 py-2 text-sm text-[#0F172A] placeholder:text-[#94A3B8] focus:border-[#4F46E5] focus:outline-none focus:ring-2 focus:ring-[#4F46E5]"
                value={episodeTitle}
                onChange={(event) => setEpisodeTitle(event.target.value)}
              />
            </div>

            <button
              type="button"
              disabled={isGenerateDisabled}
              onClick={limitReached ? () => setShowUpgradeModal(true) : () => void handleGenerate()}
              className="flex w-full items-center justify-center gap-2 rounded-lg bg-[#4F46E5] py-3 text-sm font-medium text-white shadow-sm hover:bg-[#4338CA] disabled:cursor-not-allowed disabled:opacity-60"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  <span>Generating Authority Packâ€¦</span>
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4" />
                  <span>Generate Authority Pack</span>
                </>
              )}
            </button>

            {limitReached ? (
              <div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 space-y-2">
                <p className="text-sm font-medium text-amber-800">
                  You&apos;ve reached your monthly limit
                  {effectiveLimit !== null ? ` (${packsThisMonth}/${effectiveLimit})` : ""}.
                </p>
                <p className="text-xs text-amber-700">
                  Upgrade to continue turning your source material into structured authority assets.
                </p>
                <button
                  type="button"
                  onClick={() => setShowUpgradeModal(true)}
                  className="inline-flex items-center justify-center rounded-md border border-amber-300 bg-white px-3 py-1.5 text-xs font-semibold text-amber-800 hover:bg-amber-100 transition-colors"
                >
                  View Upgrade Plans
                </button>
              </div>
            ) : null}

            {successMessage ? (
              <p className="text-center text-xs text-[#3E7A47]">{successMessage}</p>
            ) : null}
            {errorMessage ? (
              <p className="text-center text-xs text-[#A84545]">{errorMessage}</p>
            ) : null}

            {effectiveLimit !== null ? (
              <div className="space-y-2">
                <div className="h-2 w-full rounded-full bg-[#E2E8F0]">
                  <div
                    className="h-2 rounded-full bg-[#4F46E5]"
                    style={{ width: `${progressPercent}%` }}
                  />
                </div>
                <p className="text-center text-xs text-[#64748B]">
                  {packsThisMonth} of {effectiveLimit} Authority Packs used this month
                </p>
              </div>
            ) : (
              <p className="text-center text-xs text-[#64748B]">
                {packsThisMonth} Authority Packs generated this month Â· Unlimited
              </p>
            )}
          </div>
        </section>

        <section className="w-full md:w-[70%] p-8 relative flex items-start justify-center">
          <AuthorityPackPreview
            packId={activePackId}
            isGenerating={isGenerating}
            limitReached={limitReached}
            regenLimit={maxRegenerationsPerPack}
          />
        </section>
      </div>
    </>
  );
}



