"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Sparkles, Upload, Lock } from "lucide-react";
import { AuthorityPackPreview } from "./AuthorityPackPreview";
import { UpgradeModal } from "./UpgradeModal";

type PacksResponse = {
  packs?: { id: string }[];
  generated?: number;
  remaining?: number | null;
  plan?: string;
  monthlyLimit?: number | null;
  planLimits?: {
    maxRegenerationsPerPack?: number | null;
    maxStoredPacks?: number | null;
    repurposeAccess?: boolean;
    qualityFixAccess?: boolean;
  };
  code?: string;
  ok?: boolean;
  upgradeHint?: boolean;
  error?: "plan_limit_reached" | "limit_reached" | "quota" | "INVALID_INPUT" | "invalid" | "generation_failed" | "transcript_unavailable";
  detail?: string;
  message?: string;
  lastCreatedId?: string;
};

// Compact segmented control used for Input Type and Angle
function SegmentedControl({
  options,
  value,
  onChange,
  disabled,
}: {
  options: { value: string; label: string }[];
  value: string;
  onChange: (v: string) => void;
  disabled: boolean;
}) {
  return (
    <div
      style={{
        display: "inline-flex",
        backgroundColor: "#F1F5F9",
        borderRadius: "10px",
        padding: "3px",
        gap: "2px",
      }}
    >
      {options.map((opt) => {
        const active = opt.value === value;
        return (
          <button
            key={opt.value}
            type="button"
            disabled={disabled}
            onClick={() => onChange(opt.value)}
            style={{
              padding: "6px 14px",
              borderRadius: "8px",
              fontSize: "12px",
              fontWeight: active ? 600 : 500,
              color: active ? "#4F46E5" : "#64748B",
              backgroundColor: active ? "#ffffff" : "transparent",
              border: "none",
              cursor: disabled ? "not-allowed" : "pointer",
              boxShadow: active ? "0 1px 4px rgba(15,23,42,0.1)" : "none",
              transition: "all 0.15s ease",
              whiteSpace: "nowrap",
            }}
          >
            {opt.label}
          </button>
        );
      })}
    </div>
  );
}

export default function NewPackPage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const initialInput = useMemo(() => (searchParams?.get("input") ?? "").trim(), [searchParams]);
  const prefillInput = useMemo(() => (searchParams?.get("prefill") ?? "").trim(), [searchParams]);
  const sessionToken = useMemo(() => searchParams?.get("t") ?? "", [searchParams]);

  const [sourceInput, setSourceInput] = useState("");
  const [episodeTitle, setEpisodeTitle] = useState("");
  const [youtubeUrl, setYoutubeUrl] = useState("");
  const [linkedinUrl, setLinkedinUrl] = useState("");
  const [inputType, setInputType] = useState("INTERVIEW");
  const [angle, setAngle] = useState("THOUGHT_LEADERSHIP");
  const [isGenerating, setIsGenerating] = useState(false);

  const [remaining, setRemaining] = useState<number>(Infinity);
  const [monthlyLimit, setMonthlyLimit] = useState<number>(3);
  const [packsThisMonth, setPacksThisMonth] = useState<number>(0);
  const [plan, setPlan] = useState<string>("FREE");
  const [maxRegenerationsPerPack, setMaxRegenerationsPerPack] = useState<number | null>(null);
  const [countsLoaded, setCountsLoaded] = useState(false);

  const autoGeneratedRef = useRef(false);
  const abortControllerRef = useRef<AbortController | null>(null);
  const [errorMessage, setErrorMessage] = useState("");
  const [hasGenerated, setHasGenerated] = useState(false);
  const [activePackId, setActivePackId] = useState<string | null>(null);
  const [showUpgradeModal, setShowUpgradeModal] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);
  const prevSessionTokenRef = useRef(sessionToken);

  useEffect(() => {
    if (!initialInput) return;
    setSourceInput((current) => (current.trim() ? current : initialInput));
  }, [initialInput]);

  useEffect(() => {
    if (!prefillInput) return;
    setSourceInput((current) => (current.trim() ? current : prefillInput));
  }, [prefillInput]);

  useEffect(() => {
    if (!sessionToken || sessionToken === prevSessionTokenRef.current) return;
    prevSessionTokenRef.current = sessionToken;
    setActivePackId(null);
    setHasGenerated(false);
    setSourceInput("");
    setEpisodeTitle("");
    setErrorMessage("");
    autoGeneratedRef.current = false;
    textareaRef.current?.focus();
  }, [sessionToken]);

  const applyResponse = useCallback((data: PacksResponse) => {
    if (data.remaining === null) setRemaining(Infinity);
    if (typeof data.remaining === "number") setRemaining(data.remaining);
    if (data.monthlyLimit === null) setMonthlyLimit(Infinity);
    if (typeof data.monthlyLimit === "number") setMonthlyLimit(data.monthlyLimit);
    if (typeof data.generated === "number") setPacksThisMonth(data.generated);
    if (typeof data.plan === "string") setPlan(data.plan);
    if (data.planLimits && "maxRegenerationsPerPack" in data.planLimits) {
      const limit = data.planLimits.maxRegenerationsPerPack;
      setMaxRegenerationsPerPack(typeof limit === "number" ? limit : null);
    }
  }, []);

  useEffect(() => {
    const loadCounts = async () => {
      try {
        const response = await fetch("/api/packs");
        const data = (await response.json()) as PacksResponse;
        applyResponse(data);
      } catch (error) {
        console.error(error);
      } finally {
        setCountsLoaded(true);
      }
    };
    void loadCounts();
  }, [applyResponse]);

  useEffect(() => {
    if (!initialInput && countsLoaded) {
      textareaRef.current?.focus();
    }
  }, [initialInput, countsLoaded]);

  useEffect(() => {
    if (!initialInput || !countsLoaded || autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;
    void handleGenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialInput, countsLoaded]);

  const EXAMPLE_URLS = [
    { label: "Naval Ravikant Interview", url: "https://www.youtube.com/watch?v=1-TZqOsVCNM" },
    { label: "Sam Altman Talk", url: "https://www.youtube.com/watch?v=oBt53YbR9Kk" },
    { label: "Paul Graham Talk", url: "https://www.youtube.com/watch?v=f84LymEs67Y" },
  ] as const;

  const handleExampleClick = (url: string) => {
    setSourceInput(url);
    if (errorMessage) setErrorMessage("");
  };

  const handleCancel = useCallback(() => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
      abortControllerRef.current = null;
    }
    setIsGenerating(false);
    setActivePackId(null);
    setErrorMessage("");
  }, []);

  const handleGenerate = async (overrideInput?: string) => {
    const inputValue = (overrideInput ?? sourceInput).trim();
    if (isGenerating || !inputValue || remaining <= 0) return;

    const controller = new AbortController();
    abortControllerRef.current = controller;

    setIsGenerating(true);
    setActivePackId(null);
    setErrorMessage("");

    try {
      const response = await fetch("/api/packs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ input: inputValue, title: episodeTitle.trim() || undefined, inputType, angle, youtubeUrl: youtubeUrl.trim() || undefined, linkedinUrl: linkedinUrl.trim() || undefined }),
        signal: controller.signal,
      });
      let data: PacksResponse = {};
      try {
        data = (await response.json()) as PacksResponse;
      } catch {
        data = {};
      }

      const isPlanLimit =
        data.code === "PLAN_LIMIT_PACKS_EXCEEDED" ||
        data.error === "plan_limit_reached" ||
        data.error === "limit_reached" ||
        response.status === 403;
      if (isPlanLimit) {
        setRemaining(0);
        setShowUpgradeModal(true);
      } else if (data.error === "INVALID_INPUT" || data.error === "invalid") {
        setErrorMessage("Please add a valid link or transcript (min 200 characters).");
      } else if (data.error === "transcript_unavailable") {
        setErrorMessage(
          "Captions are disabled for this video. Open the video on YouTube, click ··· → Show transcript, copy the text, and paste it here directly.",
        );
      } else if (data.error === "generation_failed") {
        setErrorMessage(`Generation failed: ${data.detail ?? "unknown error"}`);
      } else if (response.ok) {
        setSourceInput("");
        setHasGenerated(true);
        if (data.lastCreatedId) {
          setActivePackId(data.lastCreatedId);
        }
      } else {
        setErrorMessage("Something went wrong. Please try again.");
      }

      applyResponse(data);
    } catch (error) {
      if (error instanceof Error && error.name === "AbortError") return;
      console.error(error);
      setErrorMessage("Something went wrong. Please try again.");
    } finally {
      abortControllerRef.current = null;
      setIsGenerating(false);
    }
  };

  const limitReached = remaining <= 0;
  const isGenerateDisabled = isGenerating || !sourceInput.trim() || limitReached;

  const effectiveLimit = monthlyLimit === Infinity ? null : monthlyLimit;

  const INPUT_TYPE_OPTIONS = [
    { value: "INTERVIEW", label: "Interview" },
    { value: "PRODUCT_UPDATE", label: "Update" },
    { value: "CUSTOMER_STORY", label: "Story" },
  ];
  const ANGLE_OPTIONS = [
    { value: "THOUGHT_LEADERSHIP", label: "Thought Leadership" },
    { value: "TACTICAL", label: "Tactical" },
    { value: "STORY_DRIVEN", label: "Story" },
  ];

  return (
    <>
      {showUpgradeModal && (
        <UpgradeModal
          currentPlan={plan}
          onClose={() => setShowUpgradeModal(false)}
        />
      )}

      <div className="flex-1 flex flex-col md:flex-row" style={{ minHeight: 0 }}>
        {/* ── Left panel ── */}
        <aside
          style={{
            width: "100%",
            maxWidth: "420px",
            flexShrink: 0,
            borderRight: "1px solid #E9EEF5",
            backgroundColor: "#FAFBFD",
            display: "flex",
            flexDirection: "column",
            padding: "28px 24px",
            gap: "20px",
            opacity: isGenerating ? 0.55 : 1,
            pointerEvents: isGenerating ? "none" : "auto",
            transition: "opacity 0.25s ease",
          }}
        >
          {/* Header row */}
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <div>
              <h1 style={{ fontSize: "18px", fontWeight: 700, color: "#0F172A", margin: 0, letterSpacing: "-0.3px" }}>
                New Authority Pack
              </h1>
              <p style={{ fontSize: "13px", color: "#94A3B8", margin: "3px 0 0", fontWeight: 400 }}>
                Paste a link or transcript below
              </p>
            </div>
            {/* Usage badge */}
            {effectiveLimit !== null && (
              <div
                style={{
                  fontSize: "11px",
                  fontWeight: 600,
                  color: limitReached ? "#DC2626" : packsThisMonth >= effectiveLimit - 1 ? "#D97706" : "#16A34A",
                  backgroundColor: limitReached ? "#FEF2F2" : packsThisMonth >= effectiveLimit - 1 ? "#FFFBEB" : "#F0FDF4",
                  border: `1px solid ${limitReached ? "#FECACA" : packsThisMonth >= effectiveLimit - 1 ? "#FDE68A" : "#BBF7D0"}`,
                  borderRadius: "100px",
                  padding: "4px 10px",
                  whiteSpace: "nowrap",
                  flexShrink: 0,
                }}
              >
                {packsThisMonth}/{effectiveLimit} used
              </div>
            )}
          </div>

          {/* Generating lock indicator */}
          {isGenerating && (
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: "8px",
                padding: "10px 14px",
                borderRadius: "10px",
                backgroundColor: "#F5F3FF",
                border: "1px solid #E0E7FF",
              }}
            >
              <Lock size={12} style={{ color: "#4F46E5", flexShrink: 0 }} />
              <span style={{ fontSize: "12px", fontWeight: 500, color: "#4338CA" }}>
                Locked while generating — nearly there…
              </span>
            </div>
          )}

          {/* Main textarea */}
          <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
            <textarea
              ref={textareaRef}
              id="source-input"
              rows={7}
              placeholder="Paste a YouTube link or transcript…"
              value={sourceInput}
              disabled={isGenerating}
              onChange={(e) => {
                setSourceInput(e.target.value);
                if (errorMessage) setErrorMessage("");
              }}
              style={{
                width: "100%",
                resize: "none",
                border: "1.5px solid #E2E8F0",
                borderRadius: "14px",
                padding: "14px 16px",
                fontSize: "14px",
                lineHeight: 1.7,
                color: "#0F172A",
                backgroundColor: "#ffffff",
                fontFamily: "inherit",
                outline: "none",
                boxSizing: "border-box",
                transition: "border-color 0.15s, box-shadow 0.15s",
                boxShadow: "0 1px 3px rgba(15,23,42,0.05)",
              }}
              onFocus={(e) => {
                e.currentTarget.style.borderColor = "#818CF8";
                e.currentTarget.style.boxShadow = "0 0 0 3px rgba(99,102,241,0.12)";
              }}
              onBlur={(e) => {
                e.currentTarget.style.borderColor = "#E2E8F0";
                e.currentTarget.style.boxShadow = "0 1px 3px rgba(15,23,42,0.05)";
              }}
            />

            {/* Upload + hint row */}
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <p style={{ fontSize: "12px", color: "#94A3B8", margin: 0 }}>
                YouTube link or raw transcript
              </p>
              <label
                htmlFor="transcript-upload"
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: "5px",
                  fontSize: "12px",
                  fontWeight: 500,
                  color: "#6366F1",
                  cursor: "pointer",
                }}
              >
                <Upload size={12} />
                Upload file
              </label>
              <input
                id="transcript-upload"
                type="file"
                className="hidden"
                accept=".txt,.srt,.vtt"
                disabled={isGenerating}
              />
            </div>
          </div>

          {/* Example prompts — only when empty */}
          {!hasGenerated && !sourceInput.trim() && (
            <div
              style={{
                borderRadius: "12px",
                border: "1px solid #E9EEF5",
                backgroundColor: "#ffffff",
                padding: "14px 16px",
              }}
            >
              <p style={{ fontSize: "11px", fontWeight: 700, color: "#94A3B8", textTransform: "uppercase", letterSpacing: "0.07em", margin: "0 0 10px" }}>
                Try an example
              </p>
              <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                {EXAMPLE_URLS.map(({ label, url }) => (
                  <button
                    key={url}
                    type="button"
                    onClick={() => handleExampleClick(url)}
                    style={{
                      textAlign: "left",
                      padding: "9px 12px",
                      borderRadius: "9px",
                      border: "1px solid #F1F5F9",
                      backgroundColor: "#F8FAFC",
                      fontSize: "13px",
                      fontWeight: 500,
                      color: "#334155",
                      cursor: "pointer",
                      transition: "all 0.15s ease",
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.borderColor = "#C7D2FE";
                      e.currentTarget.style.backgroundColor = "#EEF2FF";
                      e.currentTarget.style.color = "#4F46E5";
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.borderColor = "#F1F5F9";
                      e.currentTarget.style.backgroundColor = "#F8FAFC";
                      e.currentTarget.style.color = "#334155";
                    }}
                  >
                    {label}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Input Type + Angle — compact two-row section */}
          <div
            style={{
              borderRadius: "12px",
              border: "1px solid #E9EEF5",
              backgroundColor: "#ffffff",
              padding: "14px 16px",
              display: "flex",
              flexDirection: "column",
              gap: "12px",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px" }}>
              <span style={{ fontSize: "12px", fontWeight: 600, color: "#475569", whiteSpace: "nowrap" }}>Input Type</span>
              <SegmentedControl
                options={INPUT_TYPE_OPTIONS}
                value={inputType}
                onChange={setInputType}
                disabled={isGenerating}
              />
            </div>
            <div style={{ height: "1px", backgroundColor: "#F1F5F9" }} />
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px" }}>
              <span style={{ fontSize: "12px", fontWeight: 600, color: "#475569", whiteSpace: "nowrap" }}>Angle</span>
              <SegmentedControl
                options={ANGLE_OPTIONS}
                value={angle}
                onChange={setAngle}
                disabled={isGenerating}
              />
            </div>
          </div>

          {/* Episode title — minimal */}
          <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
            <label style={{ fontSize: "12px", fontWeight: 600, color: "#475569" }} htmlFor="episode-title">
              Title <span style={{ fontWeight: 400, color: "#94A3B8" }}>(optional)</span>
            </label>
            <input
              id="episode-title"
              type="text"
              placeholder="e.g. Naval Ravikant on wealth & happiness"
              value={episodeTitle}
              disabled={isGenerating}
              onChange={(e) => setEpisodeTitle(e.target.value)}
              style={{
                width: "100%",
                border: "1.5px solid #E2E8F0",
                borderRadius: "10px",
                padding: "10px 14px",
                fontSize: "13px",
                color: "#0F172A",
                backgroundColor: "#ffffff",
                fontFamily: "inherit",
                outline: "none",
                boxSizing: "border-box",
                transition: "border-color 0.15s, box-shadow 0.15s",
              }}
              onFocus={(e) => {
                e.currentTarget.style.borderColor = "#818CF8";
                e.currentTarget.style.boxShadow = "0 0 0 3px rgba(99,102,241,0.1)";
              }}
              onBlur={(e) => {
                e.currentTarget.style.borderColor = "#E2E8F0";
                e.currentTarget.style.boxShadow = "none";
              }}
            />
          </div>

          {/* YouTube URL + LinkedIn URL — only when pasting raw transcript for an interview */}
          {inputType === "INTERVIEW" && sourceInput.trim() && !/^https?:\/\//i.test(sourceInput.trim()) && (
            <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
              <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                <label style={{ fontSize: "12px", fontWeight: 600, color: "#475569" }} htmlFor="youtube-url">
                  YouTube URL <span style={{ fontWeight: 400, color: "#94A3B8" }}>(optional — for outreach)</span>
                </label>
                <input
                  id="youtube-url"
                  type="url"
                  placeholder="https://youtube.com/watch?v=..."
                  value={youtubeUrl}
                  disabled={isGenerating}
                  onChange={(e) => setYoutubeUrl(e.target.value)}
                  style={{
                    width: "100%",
                    border: "1.5px solid #E2E8F0",
                    borderRadius: "10px",
                    padding: "10px 14px",
                    fontSize: "13px",
                    color: "#0F172A",
                    backgroundColor: "#ffffff",
                    fontFamily: "inherit",
                    outline: "none",
                    boxSizing: "border-box",
                    transition: "border-color 0.15s, box-shadow 0.15s",
                  }}
                  onFocus={(e) => {
                    e.currentTarget.style.borderColor = "#818CF8";
                    e.currentTarget.style.boxShadow = "0 0 0 3px rgba(99,102,241,0.1)";
                  }}
                  onBlur={(e) => {
                    e.currentTarget.style.borderColor = "#E2E8F0";
                    e.currentTarget.style.boxShadow = "none";
                  }}
                />
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                <label style={{ fontSize: "12px", fontWeight: 600, color: "#475569" }} htmlFor="linkedin-url">
                  Founder LinkedIn URL <span style={{ fontWeight: 400, color: "#94A3B8" }}>(optional — helps find email)</span>
                </label>
                <input
                  id="linkedin-url"
                  type="url"
                  placeholder="https://linkedin.com/in/founder-name"
                  value={linkedinUrl}
                  disabled={isGenerating}
                  onChange={(e) => setLinkedinUrl(e.target.value)}
                  style={{
                    width: "100%",
                    border: "1.5px solid #E2E8F0",
                    borderRadius: "10px",
                    padding: "10px 14px",
                    fontSize: "13px",
                    color: "#0F172A",
                    backgroundColor: "#ffffff",
                    fontFamily: "inherit",
                    outline: "none",
                    boxSizing: "border-box",
                    transition: "border-color 0.15s, box-shadow 0.15s",
                  }}
                  onFocus={(e) => {
                    e.currentTarget.style.borderColor = "#818CF8";
                    e.currentTarget.style.boxShadow = "0 0 0 3px rgba(99,102,241,0.1)";
                  }}
                  onBlur={(e) => {
                    e.currentTarget.style.borderColor = "#E2E8F0";
                    e.currentTarget.style.boxShadow = "none";
                  }}
                />
              </div>
            </div>
          )}

          {/* Generate button */}
          <button
            type="button"
            disabled={isGenerateDisabled}
            onClick={limitReached ? () => setShowUpgradeModal(true) : () => void handleGenerate()}
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              gap: "8px",
              width: "100%",
              padding: "14px 24px",
              borderRadius: "12px",
              border: "none",
              background: isGenerateDisabled
                ? "linear-gradient(135deg, #A5B4FC 0%, #C4B5FD 100%)"
                : "linear-gradient(135deg, #4F46E5 0%, #7C3AED 100%)",
              color: "#ffffff",
              fontWeight: 700,
              fontSize: "15px",
              cursor: isGenerateDisabled ? "not-allowed" : "pointer",
              boxShadow: isGenerateDisabled ? "none" : "0 4px 20px rgba(79,70,229,0.38)",
              transition: "all 0.2s ease",
              letterSpacing: "0.01em",
            }}
            onMouseEnter={(e) => {
              if (!isGenerateDisabled) {
                e.currentTarget.style.transform = "translateY(-1px)";
                e.currentTarget.style.boxShadow = "0 8px 28px rgba(79,70,229,0.45)";
              }
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.transform = "translateY(0)";
              e.currentTarget.style.boxShadow = isGenerateDisabled ? "none" : "0 4px 20px rgba(79,70,229,0.38)";
            }}
          >
            <Sparkles size={16} strokeWidth={2} />
            {isGenerating ? "Generating…" : "Generate Authority Pack"}
          </button>

          {/* Error */}
          {errorMessage && (
            <p style={{ fontSize: "13px", color: "#DC2626", textAlign: "center", margin: 0, lineHeight: 1.5 }}>
              {errorMessage}
            </p>
          )}

          {/* Limit reached */}
          {limitReached && (
            <div
              style={{
                borderRadius: "12px",
                border: "1px solid #FDE68A",
                backgroundColor: "#FFFBEB",
                padding: "14px 16px",
              }}
            >
              <p style={{ fontSize: "13px", fontWeight: 600, color: "#92400E", margin: "0 0 4px" }}>
                Monthly limit reached
                {effectiveLimit !== null ? ` — ${packsThisMonth}/${effectiveLimit} packs` : ""}
              </p>
              <p style={{ fontSize: "12px", color: "#B45309", margin: "0 0 12px", lineHeight: 1.5 }}>
                Upgrade to continue generating authority content.
              </p>
              <button
                type="button"
                onClick={() => setShowUpgradeModal(true)}
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  justifyContent: "center",
                  padding: "8px 16px",
                  borderRadius: "8px",
                  border: "1px solid #FCD34D",
                  backgroundColor: "#ffffff",
                  fontSize: "12px",
                  fontWeight: 600,
                  color: "#92400E",
                  cursor: "pointer",
                }}
              >
                View Upgrade Plans
              </button>
            </div>
          )}
        </aside>

        {/* ── Right panel ── */}
        <section
          style={{
            flex: 1,
            padding: "28px 32px",
            display: "flex",
            alignItems: "flex-start",
            justifyContent: "center",
            backgroundColor: "#F8FAFC",
            minWidth: 0,
          }}
        >
          <AuthorityPackPreview
            packId={activePackId}
            isGenerating={isGenerating}
            limitReached={limitReached}
            regenLimit={maxRegenerationsPerPack}
            onCancel={handleCancel}
          />
        </section>
      </div>
    </>
  );
}
