"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Loader2, Sparkles } from "lucide-react";
import { AuthorityPackPreview } from "./AuthorityPackPreview";

type PacksResponse = {
  generated?: number;
  remaining?: number;
  error?: "quota" | "invalid" | "generation_failed" | "transcript_unavailable";
  detail?: string;
  lastCreatedId?: string;
};

const MAX_FREE_PACKS = 3;

export default function NewPackPage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const initialInput = useMemo(() => (searchParams?.get("input") ?? "").trim(), [searchParams]);

  const [sourceInput, setSourceInput] = useState("");
  const [episodeTitle, setEpisodeTitle] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [remainingFreePacks, setRemainingFreePacks] = useState(MAX_FREE_PACKS);
  const [countsLoaded, setCountsLoaded] = useState(false);
  const autoGeneratedRef = useRef(false);
  const [successMessage, setSuccessMessage] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const [hasGenerated, setHasGenerated] = useState(false);
  const [activePackId, setActivePackId] = useState<string | null>(null);

  useEffect(() => {
    if (!initialInput) return;
    setSourceInput((current) => (current.trim() ? current : initialInput));
  }, [initialInput]);

  const applyResponse = useCallback((data: PacksResponse) => {
    const nextGenerated = typeof data.generated === "number" ? data.generated : 0;
    const nextRemaining =
      typeof data.remaining === "number"
        ? data.remaining
        : Math.max(0, MAX_FREE_PACKS - nextGenerated);
    setRemainingFreePacks(nextRemaining);
  }, []);

  useEffect(() => {
    const loadCounts = async () => {
      try {
        const response = await fetch("/api/packs");
        const data = (await response.json()) as PacksResponse;
        applyResponse(data);
      } catch (error) {
        console.error(error);
      } finally {
        setCountsLoaded(true);
      }
    };

    void loadCounts();
  }, [applyResponse]);

  useEffect(() => {
    if (!initialInput || !countsLoaded || autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;
    void handleGenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialInput, countsLoaded]);

  const handleGenerate = async () => {
    const inputValue = sourceInput.trim();
    if (isGenerating || !inputValue || remainingFreePacks === 0) {
      return;
    }

    setIsGenerating(true);
    setSuccessMessage("");
    setErrorMessage("");

    try {
      const response = await fetch("/api/packs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ input: inputValue, title: episodeTitle.trim() || undefined }),
      });
      const data = (await response.json()) as PacksResponse;

      if (data.error === "quota") {
        setErrorMessage("Free plan limit reached.");
      } else if (data.error === "invalid") {
        setErrorMessage("Please add a valid link or transcript.");
      } else if (data.error === "transcript_unavailable") {
        setErrorMessage(
          "Captions are disabled for this video. Open the video on YouTube, click \u22EF \u2192 Show transcript, copy the text, and paste it here directly.",
        );
      } else if (data.error === "generation_failed") {
        setErrorMessage(`Generation failed: ${data.detail ?? "unknown error"}`);
      } else if (response.ok) {
        setSourceInput("");
        setSuccessMessage("Pack generated.");
        setHasGenerated(true);
        if (data.lastCreatedId) {
          setActivePackId(data.lastCreatedId);
        }
      } else {
        setErrorMessage("Something went wrong. Please try again.");
      }

      applyResponse(data);
    } catch (error) {
      console.error(error);
      setErrorMessage("Something went wrong. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const isGenerateDisabled =
    isGenerating || !sourceInput.trim() || remainingFreePacks === 0;
  const generatedCount = Math.max(0, MAX_FREE_PACKS - remainingFreePacks);
  const progressPercent = Math.min(
    100,
    Math.round((generatedCount / MAX_FREE_PACKS) * 100),
  );

  return (
    <div className="flex-1 flex flex-col md:flex-row">
      <section className="w-full md:w-[30%] border-b border-[#E2E8F0] md:border-b-0 md:border-r p-8">
        <div className="space-y-2">
          <h2 className="text-lg font-semibold">Source</h2>
          <p className="text-sm text-[#64748B]">
            Provide a YouTube link or transcript to generate your authority
            pack.
          </p>
        </div>

        <div className="mt-6 space-y-5">
          <div className="space-y-2">
            <label className="text-sm font-medium text-[#334155]" htmlFor="source-input">
              Input
            </label>
            <textarea
              id="source-input"
              rows={6}
              placeholder="Paste YouTube link or transcript..."
              className="w-full resize-none rounded-lg border border-[#E2E8F0] bg-white px-3 py-2 text-sm text-[#0F172A] placeholder:text-[#94A3B8] focus:border-[#4F46E5] focus:outline-none focus:ring-2 focus:ring-[#4F46E5]"
              value={sourceInput}
              disabled={remainingFreePacks === 0 || isGenerating}
              onChange={(event) => {
                setSourceInput(event.target.value);
                if (errorMessage) {
                  setErrorMessage("");
                }
                if (successMessage) {
                  setSuccessMessage("");
                }
              }}
            />
          </div>

          <div>
            <label
              htmlFor="transcript-upload"
              className="flex cursor-pointer flex-col items-center justify-center gap-1 rounded-lg border-2 border-dashed border-[#E2E8F0] px-6 py-8 text-center text-sm text-[#64748B] hover:bg-[#F1F5F9]"
            >
              <span className="font-medium text-[#475569]">
                Click to upload or drag and drop
              </span>
              <span className="text-xs text-[#94A3B8]">.txt, .srt, .vtt files</span>
            </label>
            <input
              id="transcript-upload"
              type="file"
              className="hidden"
              accept=".txt,.srt,.vtt"
            />
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium text-[#334155]" htmlFor="episode-title">
              Episode Title
            </label>
            <input
              id="episode-title"
              type="text"
              placeholder="Enter episode title..."
              className="w-full rounded-lg border border-[#E2E8F0] bg-white px-3 py-2 text-sm text-[#0F172A] placeholder:text-[#94A3B8] focus:border-[#4F46E5] focus:outline-none focus:ring-2 focus:ring-[#4F46E5]"
              value={episodeTitle}
              onChange={(event) => setEpisodeTitle(event.target.value)}
            />
          </div>

          <button
            type="button"
            disabled={isGenerateDisabled}
            onClick={handleGenerate}
            className="flex w-full items-center justify-center gap-2 rounded-lg bg-[#4F46E5] py-3 text-sm font-medium text-white shadow-sm hover:bg-[#4338CA] disabled:cursor-not-allowed disabled:opacity-60"
          >
            {isGenerating ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                <span>Generating Authority Pack…</span>
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" />
                <span>Generate Authority Pack</span>
              </>
            )}
          </button>
          {successMessage ? (
            <p className="text-center text-xs text-[#3E7A47]">
              {successMessage}
            </p>
          ) : null}
          {errorMessage ? (
            <p className="text-center text-xs text-[#A84545]">{errorMessage}</p>
          ) : null}

          <div className="space-y-2">
            <div className="h-2 w-full rounded-full bg-[#E2E8F0]">
              <div
                className="h-2 rounded-full bg-[#4F46E5]"
                style={{ width: `${progressPercent}%` }}
              />
            </div>
            <p className="text-center text-xs text-[#64748B]">
              {generatedCount} of {MAX_FREE_PACKS} free packs used
            </p>
          </div>
        </div>
      </section>

      <section className="w-full md:w-[70%] p-8 relative flex items-start justify-center">
        <AuthorityPackPreview packId={activePackId} isGenerating={isGenerating} />
      </section>
    </div>
  );
}
